social_media/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='user_logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

social_media/posts/urls.py
from django.urls import path, include
from . import views

app_name='posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>', views.DeletePost.as_view(), name='delete'),

]

social_media/social_media/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('test/', views.TestPage.as_view(), name='test'),
    path('thanks/', views.ThanksPage.as_view(), name='thanks'),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    path('', views.HomePage.as_view(), name='home'),
]

social_media/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Social Media</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap-theme.min.css" integrity="sha384-6pzBo3FDv/PJ8r2KRkGHifhEocL+1X2rVCTTkUfGk7/0pbek5mMa1upzvWbrUbOZ" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>

    <!--Google Font-->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'css/master.css' %}">

</head>
<body>
<nav class="navbar mynav" role="navigation" id="navbar">
    <div class="container">
        <a class="navbar-brand mynav" href="{% url 'home' %}">Social Media</a>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><a href="{% url 'posts:create' %}">Post</a></li>
                <li><a href="{% url 'groups:all' %}">Groups</a></li>
                <li><a href="{% url 'groups:create' %}">Create Group</a></li>
                <li><a href="{% url 'accounts:user_logout' %}">Logout</a></li>
            {% else %}
                <li><a href="{% url 'groups:all' %}">Groups</a></li>
                <li><a href="{% url 'accounts:login' %}">Login</a></li>
                <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
            {% endif %}
        </ul>
    </div>
</nav>

<div class="container mycontent">
    {% block content %}
    {% endblock %}
</div>
<canvas id="canvas"></canvas>
</body>

<script type="text/javascript" src="{% static 'js/master.js' %}"></script>

</html>

social_media/templates/index.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome to Social Media!</h1>
{% endblock %}

social_media/templates/test.html
{% extends 'base.html' %}
{% block content %}
<h1>You are logged in!</h1>
{% endblock %}

social_media/templates/thanks.html
{% extends 'base.html' %}
{% block content %}
<h1>Thanks for visiting!</h1>
{% endblock %}